/**
 * Paragraphes citables (RECETTE §21).
 *
 * Chaque page s'ouvrait sur un titre et une phrase de vingt mots : rien qu'un
 * moteur de reponse puisse extraire. Le bloc ci-dessous fait au moins 120 mots,
 * se place avant tout le reste du corps, et dit ce que la page etablit. Un texte
 * par anciennete et un par guide : un paragraphe generique se serait repete
 * quinze fois, et check-unique neutralise les chiffres.
 */

export const CITABLE_ANCIENNETE: Record<number, string> = {
  1: "Après un an d'ancienneté, le droit à l'indemnité légale de licenciement est acquis : l'article L1234-9 du Code du travail l'ouvre dès huit mois de présence continue, et le montant se calcule au quart de mois de salaire par année. Une seule année donne donc un quart de mois, auquel s'ajoute le prorata des mois entamés au-delà. C'est le seuil où la question du salaire de référence pèse le plus sur le résultat, puisque la formule retient le plus favorable entre la moyenne des douze derniers mois et celle des trois derniers, primes incluses au prorata. À ce niveau d'ancienneté, l'indemnité compensatrice de préavis, d'un mois, dépasse souvent l'indemnité de licenciement elle-même. Vérifier ce salaire de référence est donc le premier geste utile.",
  5: "Après cinq ans d'ancienneté, l'indemnité légale de licenciement représente un quart de mois de salaire par année, soit un mois et un quart de salaire de référence, auquel s'ajoute le prorata des mois entamés. Le préavis passe à deux mois, l'ancienneté dépassant deux ans, et l'indemnité compensatrice correspondante s'ajoute au solde de tout compte si l'employeur dispense le salarié de l'exécuter. À ce stade, le calcul reste entièrement dans la première tranche du barème : le taux majoré d'un tiers de mois par année ne s'applique qu'à partir de la onzième. La convention collective peut prévoir mieux, et c'est le montant le plus favorable qui s'applique, jamais la somme des deux. La comparaison des deux barèmes se fait sur le montant total, pas ligne à ligne.",
  10: "Après dix ans d'ancienneté, l'indemnité légale de licenciement atteint deux mois et demi de salaire de référence, au taux d'un quart de mois par année. C'est la dernière année avant le changement de barème : à partir de la onzième, chaque année supplémentaire compte pour un tiers de mois et non plus pour un quart, si bien qu'un licenciement notifié quelques semaines plus tard n'a pas le même coût. Le préavis est de deux mois. À ce niveau d'ancienneté, la comparaison avec l'indemnité conventionnelle devient décisive : plusieurs branches prévoient des barèmes nettement supérieurs au minimum légal dès dix ans, et c'est le plus favorable des deux qui est dû. Le passage au taux majoré rend la date de notification déterminante.",
  15: "Après quinze ans d'ancienneté, l'indemnité légale de licenciement se calcule en deux tranches : un quart de mois de salaire par année pour les dix premières, un tiers de mois par année au-delà. Quinze ans donnent donc deux mois et demi pour les dix premières années, plus un mois et deux tiers pour les cinq suivantes, soit environ quatre mois et un sixième de salaire de référence. Le préavis reste de deux mois. À ce stade, la part supra-légale négociée devient un enjeu fiscal : elle n'est exonérée d'impôt que dans la limite du plus élevé entre deux fois la rémunération annuelle brute, la moitié de l'indemnité totale, et six fois le plafond annuel de la Sécurité sociale. Au-delà de ces limites, la fraction excédentaire est imposée comme un salaire.",
  20: "Après vingt ans d'ancienneté, l'indemnité légale de licenciement combine les deux tranches du barème : deux mois et demi de salaire pour les dix premières années, puis un tiers de mois par année pour les dix suivantes, soit environ cinq mois et cinq sixièmes de salaire de référence au total. Le préavis est de deux mois. À ce niveau, l'indemnité dépasse souvent le plafond d'exonération de cotisations sociales, fixé à deux fois le plafond annuel de la Sécurité sociale, et la fraction excédentaire est soumise aux cotisations comme un salaire. La convention collective de branche prévoit fréquemment un barème plus généreux à partir de quinze ou vingt ans, et c'est alors elle qui s'applique. Le solde de tout compte doit détailler chaque poste séparément pour être vérifiable.",
  25: "Après vingt-cinq ans d'ancienneté, l'indemnité légale de licenciement atteint environ sept mois et demi de salaire de référence : deux mois et demi au titre des dix premières années, puis un tiers de mois pour chacune des quinze suivantes. Le préavis reste fixé à deux mois par la loi, mais la convention collective l'allonge souvent à trois pour les cadres. À ce niveau d'ancienneté, deux vérifications s'imposent avant d'accepter un solde de tout compte : le salaire de référence doit intégrer les primes et le treizième mois au prorata, et le barème conventionnel doit être comparé au barème légal, l'employeur devant appliquer le plus favorable des deux sans jamais les cumuler. Un désaccord sur le salaire de référence se conteste devant le conseil de prud'hommes.",
  30: "Après trente ans d'ancienneté, l'indemnité légale de licenciement s'élève à environ neuf mois et un sixième de salaire de référence : deux mois et demi pour les dix premières années, puis un tiers de mois pour chacune des vingt suivantes. C'est le niveau où l'écart entre barème légal et barème conventionnel devient le plus important, plusieurs branches prévoyant jusqu'à un mois par année d'ancienneté pour les cadres, sous un plafond exprimé en mois. C'est aussi le niveau où la part exonérée d'impôt et de cotisations atteint ses limites : au-delà de six fois le plafond annuel de la Sécurité sociale, la fraction supra-légale est imposable, et au-delà de deux fois ce plafond elle supporte les cotisations. Le plafond conventionnel, exprimé en mois, devient alors la limite qui joue réellement.",
};

export const CITABLE_PAGE: Record<string, string> = {
  glossaire:
    "Le vocabulaire du licenciement mélange des termes légaux, des termes conventionnels et des termes d'usage, et la confusion entre deux d'entre eux coûte de l'argent. L'indemnité légale de licenciement, prévue à l'article L1234-9 du Code du travail, n'est pas l'indemnité compensatrice de préavis, qui remplace un salaire non versé, ni l'indemnité compensatrice de congés payés, qui solde des jours acquis. L'ancienneté ne se confond pas avec la durée du contrat, puisqu'un congé parental ne compte que pour moitié. Le salaire de référence n'est pas le dernier salaire, mais le plus favorable de deux moyennes. Ce glossaire définit chaque terme dans le sens que lui donnent les textes, et indique où il figure sur un bulletin ou dans un solde de tout compte. Il renvoie enfin, pour chaque terme, à la page qui le traite au fond.",
  "guide-are":
    "L'allocation d'aide au retour à l'emploi et l'indemnité de licenciement ne s'additionnent pas librement : l'indemnité supra-légale, c'est-à-dire la part versée au-delà du minimum légal, décale le point de départ du versement de l'allocation. France Travail applique un différé spécifique égal à cette part divisée par un coefficient, plafonné à cent cinquante jours, et ce différé s'ajoute au différé de congés payés ainsi qu'au délai d'attente de sept jours. Négocier une indemnité de départ plus élevée revient donc à avancer de la trésorerie contre un report d'allocation, et l'arbitrage dépend de la durée prévisible de recherche d'emploi. Ce guide détaille le calcul du différé, les cas où il ne s'applique pas, et l'ordre dans lequel les délais se cumulent. Il indique aussi comment le différé se calcule quand plusieurs indemnités sont versées.",
  guides:
    "Les guides réunis ici traitent les situations où le calcul de l'indemnité ne suffit pas à répondre à la question posée. Le motif du licenciement change les droits : une faute grave supprime l'indemnité et le préavis, une inaptitude d'origine professionnelle double l'indemnité légale, un licenciement économique ouvre des droits d'accompagnement propres. La forme de la rupture compte aussi, l'indemnité de rupture conventionnelle ne pouvant être inférieure à l'indemnité légale. Restent deux sujets transversaux, la fiscalité de ce qui est versé et les voies de contestation devant le conseil de prud'hommes, avec leurs délais de forclusion. Chaque guide indique le texte applicable et ce qui se vérifie sur un solde de tout compte. Chacun signale enfin ce qu'il ne traite pas, pour éviter de s'y fier au-delà de son objet.",
  "guides/preavis-licenciement":
    "La durée du préavis de licenciement dépend de la seule ancienneté : aucune pour moins de six mois, un mois entre six mois et deux ans, deux mois au-delà, la convention collective pouvant prévoir davantage, notamment trois mois pour les cadres. Le préavis se distingue de l'indemnité de licenciement : il correspond à du travail dû, et non à une réparation. Lorsque l'employeur dispense le salarié de l'exécuter, il verse une indemnité compensatrice d'un montant égal au salaire qu'aurait produit cette période, primes comprises, et cette somme est imposable comme un salaire. La dispense ne réduit ni l'ancienneté acquise, ni le montant de l'indemnité de licenciement, ni les congés payés qui continuent de se constituer pendant la période. Elle ne modifie pas non plus la date de fin de contrat inscrite sur l'attestation.",
  "guides/licenciement-economique":
    "Un licenciement économique n'est pas défini par la situation de l'entreprise mais par la suppression ou la transformation d'un emploi, ou par la modification refusée d'un élément essentiel du contrat, pour un motif non inhérent à la personne du salarié. L'indemnité légale de licenciement est la même que pour un motif personnel, mais la procédure ajoute des obligations : recherche de reclassement, critères d'ordre des licenciements, information de l'administration, et proposition du contrat de sécurisation professionnelle pour les entreprises de moins de mille salariés. Le refus du contrat de sécurisation professionnelle ramène le salarié au régime de droit commun avec préavis, et son acceptation le prive du préavis tout en ouvrant une allocation supérieure. Le choix entre les deux se fait dans un délai de vingt et un jours.",
  "guides/licenciement-inaptitude":
    "L'inaptitude constatée par le médecin du travail ne permet un licenciement qu'après une recherche de reclassement documentée, ou lorsque l'avis mentionne expressément que tout maintien dans un emploi serait préjudiciable à la santé. L'origine de l'inaptitude commande ensuite le montant : lorsqu'elle résulte d'un accident du travail ou d'une maladie professionnelle, l'article L1226-14 du Code du travail double l'indemnité légale de licenciement et ajoute une indemnité équivalente au préavis, bien que celui-ci ne soit pas exécuté. Lorsque l'inaptitude est d'origine non professionnelle, l'indemnité reste celle de droit commun et le préavis n'est ni exécuté ni indemnisé. La contestation de l'avis d'inaptitude relève du conseil de prud'hommes, dans un délai de quinze jours. Le délai court à compter de la notification de l'avis au salarié.",
  "guides/fiscalite-indemnites":
    "L'indemnité légale de licenciement est intégralement exonérée d'impôt sur le revenu et de cotisations sociales, quel que soit son montant. Ce qui se taxe, c'est la part versée au-delà de ce minimum. Cette part supra-légale échappe à l'impôt dans la limite du plus élevé de trois plafonds : deux fois la rémunération annuelle brute de l'année précédente, la moitié de l'indemnité totale, ou six fois le plafond annuel de la Sécurité sociale. Les cotisations sociales suivent une règle distincte, avec une exonération limitée à deux fois ce plafond, et la CSG-CRDS s'applique dès le premier euro supra-légal. L'indemnité compensatrice de préavis et celle de congés payés, elles, sont imposables comme des salaires. Le bulletin de paie doit distinguer ces lignes, faute de quoi le calcul n'est pas vérifiable.",
  "guides/contestation-prud-hommes":
    "La contestation d'un licenciement devant le conseil de prud'hommes se heurte d'abord à des délais : douze mois à compter de la notification pour contester la rupture elle-même, trois ans pour réclamer un rappel de salaire, et deux ans pour une action née de l'exécution du contrat. Passés ces délais, la demande est irrecevable quel que soit son bien-fondé. Sur le fond, l'absence de cause réelle et sérieuse ouvre droit à une indemnité fixée dans les limites du barème de l'article L1235-3, exprimé en mois de salaire selon l'ancienneté. Une irrégularité de procédure, elle, n'entraîne qu'une indemnité distincte et n'annule pas le licenciement. La saisine se fait par requête, sans avocat obligatoire. La conciliation préalable est obligatoire et peut aboutir à une indemnité forfaitaire barémée.",
};
